license_family:
  - lgpl
  - gpl
c_stdlib_version:   # [osx and x86_64]
  - "10.13"         # [osx and x86_64]
# Needed for static_assert and c11 definitions
c_stdlib_version:          # [linux]
  - "2.17"                 # [linux]
